import { ComponentHeadingTypography } from '@components/styles/ComponentsStyles';
import { Box, Container, Typography } from '@mui/material';
import { ComponentTopSpacing } from '@styles/globalMuiStyles';
const PrivacyPolicy = () => {
	return (
		<>
			<ComponentTopSpacing />
			<Container maxWidth="xl">
				<Box>
					<ComponentHeadingTypography variant="h6">
						Privacy Policy
					</ComponentHeadingTypography>
				</Box>
				<Box mt={1}>
					<Box sx={{ mb: 1 }}>Last updated: February 24, 2021</Box>
					<Box sx={{ mb: 1, mt: 2 }}>
						This Privacy Policy describes Our policies and
						procedures on the collection, use and disclosure of Your
						information when You use the Service and tells You about
						Your privacy rights and how the law protects You.
					</Box>
					<Box sx={{ mb: 2, mt: 3 }}>
						We use Your Personal data to provide and improve the
						Service. By using the Service, You agree to the
						collection and use of information in accordance with
						this Privacy Policy.
					</Box>
					<Box sx={{ mb: 1 }}>
						Interpretation and Definitions
						<br></br>Interpretation <br></br>
						The words of which the initial letter is capitalized
						have meanings defined under the following conditions.
						The following definitions shall have the same meaning
						regardless of whether they appear in singular or in
						plural.
						<Box mt={2} mb={1}>
							{' '}
							Definitions <br></br>
							For the purposes of of this Privacy Policy:{' '}
						</Box>
					</Box>
					<Box sx={{ mb: 1 }}>
						<Box mt={2} mb={1}>
							<b>Account</b> means a unique account created for
							You to access our Service or parts of our Service.
						</Box>

						<Box mt={2} mb={1}>
							<b>Affiliate</b> means an entity that controls, is
							controlled by or is under common control with a
							party, where {"'control'"} means ownership of 50% or
							more of the shares, equity interest or other
							securities entitled to vote for election of
							directors or other managing authority.
						</Box>

						<Box mt={2} mb={1}>
							<b>Application</b> means the software program
							provided by the Company downloaded by You on any
							electronic device, named UMEGO
						</Box>

						<Box mt={2} mb={1}>
							<b>Company</b> (referred to as either{' '}
							{"'the Company'"},{"'We'"}, {"'Us'"} or {"'Our'"} in
							this Agreement) refers to Meetlandia Limited, 14/F,
							Manning House, 38-48 Queen’s Road Central, Central,
							Hong Kong.
						</Box>

						<Box mt={2} mb={1}>
							<b>Cookies</b> are small files that are placed on
							Your computer, mobile device or any other device by
							a website, containing the details of Your browsing
							history on that website among its many uses.
						</Box>

						<Box mt={2} mb={1}>
							<b>Country</b> refers to: Hong Kong SAR China
						</Box>

						<Box mt={2} mb={1}>
							<b>Device</b> means any device that can access the
							Service such as a computer, a cellphone or a digital
							tablet.
						</Box>

						<Box mt={2} mb={1}>
							<b>Personal Data</b> is any information that relates
							to an identified or identifiable individual.
						</Box>

						<Box mt={2} mb={1}>
							<b>Service</b> refers to the Application or the
							Website or both.
						</Box>

						<Box mt={2} mb={1}>
							<b>Service Provider</b> means any natural or legal
							person who processes the data on behalf of the
							Company. It refers to third-party companies or
							individuals employed by the Company to facilitate
							the Service, to provide the Service on behalf of the
							Company, to perform services related to the Service
							or to assist the Company in analyzing how the
							Service is used.
						</Box>

						<Box mt={2} mb={1}>
							<b>Third-party Social Media Service</b> refers to
							any website or any social network website through
							which a User can log in or create an account to use
							the Service.
						</Box>

						<Box mt={2} mb={1}>
							<b>Usage Data</b> refers to data collected
							automatically, either generated by the use of the
							Service or from the Service infrastructure itself
							(for example, the duration of a page visit).
						</Box>

						<Box mt={2} mb={1}>
							<b>Website</b> refers to UMEGO, accessible from
							www.umego.io
						</Box>

						<Box mt={2} mb={1}>
							<b>You</b> means the individual accessing or using
							the Service, or the company, or other legal entity
							on behalf of which such individual is accessing or
							using the Service, as applicable.
						</Box>
					</Box>
					<Box sx={{ mb: 1, mt: 5 }}>
						Collecting and Using Your Personal Data
						<br></br>
						Types of Data Collected
						<br></br>
						<br></br>
						<br></br>
						<h2>Personal Data</h2>
						<Box mt={2} mb={2}>
							While using Our Service, We may ask You to provide
							Us with certain personally identifiable information
							that can be used to contact or identify You.
							Personally identifiable information may include, but
							is not limited to:
						</Box>
						<Box mt={2} mb={2}>
							Email address
						</Box>
						<Box mt={2} mb={2}>
							First name and last name
						</Box>
						<Box mt={2} mb={2}>
							Phone number Address, State, Province, ZIP/Postal
							code, City
						</Box>
						<Box mt={2} mb={5}>
							Usage Data
						</Box>
					</Box>
					<h2>Usage Data</h2>
					<Box mt={2} mb={2}>
						Usage Data is collected automatically when using the
						Service.
					</Box>
					<Box mt={2} mb={2}>
						Usage Data may include information such as Your{' '}
						{"Device's"}
						Internet Protocol address (e.g. IP address), browser
						type, browser version, the pages of our Service that You
						visit, the time and date of Your visit, the time spent
						on those pages, unique device identifiers and other
						diagnostic data.
					</Box>
					<Box mt={2} mb={2}>
						When You access the Service by or through a mobile
						device, We may collect certain information
						automatically, including, but not limited to, the type
						of mobile device You use, Your mobile device unique ID,
						the IP address of Your mobile device, Your mobile
						operating system, the type of mobile Internet browser
						You use, unique device identifiers and other diagnostic
						data.
					</Box>
					<Box mt={2} mb={5}>
						We may also collect information that Your browser sends
						whenever You visit our Service or when You access the
						Service by or through a mobile device.
					</Box>
					<h2>Information from Third-Party Social Media Services</h2>
					<Box mt={2} mb={2}>
						The Company allows You to create an account and log in
						to use the Service through the following Third-party
						Social Media Services:
					</Box>
					<Box mt={2} mb={2}>
						Google<br></br> Facebook <br></br>Twitter
					</Box>
					<Box mt={2} mb={2}>
						If You decide to register through or otherwise grant us
						access to a Third-Party Social Media Service, We may
						collect Personal data that is already associated with
						Your Third-Party Social Media {"Service's"} account,
						such as Your name, Your email address, Your activities
						or Your contact list associated with that account.
					</Box>
					<Box mt={2} mb={2}>
						You may also have the option of sharing additional
						information with the Company through Your Third-Party
						Social Media {"Service's"} account. If You choose to
						provide such information and Personal Data, during
						registration or otherwise, You are giving the Company
						permission to use, share, and store it in a manner
						consistent with this Privacy Policy.
					</Box>
					<Typography
						variant="h5"
						sx={{
							mb: 1,
							mt: 2,
							fontWeight: 'bolder',
						}}
					>
						Information Collected while Using the Application
					</Typography>
					<Box sx={{ mb: 1, mt: 2 }}>
						While using Our Application, in order to provide
						features of Our Application, We may collect, with Your
						prior permission:
						<Box mt={2} mb={2}>
							Information regarding your location
						</Box>
						<Box mt={2} mb={2}>
							Pictures and other information from your{' '}
							{"Device's"}
							camera and photo library
						</Box>
						<Box mt={2} mb={2}>
							We use this information to provide features of Our
							Service, to improve and customize Our Service. The
							information may be uploaded to the {"Company's"}{' '}
							servers and/or a Service {"Provider's"} server or it
							may be simply stored on Your device.
						</Box>
						<Box mt={2} mb={2}>
							You can enable or disable access to this information
							at any time, through Your Device settings.
						</Box>
						<Typography
							variant="h5"
							sx={{
								mb: 1,
								mt: 3,
								fontWeight: 'bolder',
							}}
						>
							Tracking Technologies and Cookies
						</Typography>
						<Box mt={2} mb={2}>
							We use Cookies and similar tracking technologies to
							track the activity on Our Service and store certain
							information. Tracking technologies used are beacons,
							tags, and scripts to collect and track information
							and to improve and analyze Our Service. The
							technologies We use may include:
						</Box>
						<Box mt={2} mb={2}>
							<Box mt={2} mb={1}>
								<b>Cookies or Browser Cookies.</b> A cookie is a
								small file placed on Your Device. You can
								instruct Your browser to refuse all Cookies or
								to indicate when a Cookie is being sent.
								However, if You do not accept Cookies, You may
								not be able to use some parts of our Service.
								Unless you have adjusted Your browser setting so
								that it will refuse Cookies, our Service may use
								Cookies.
							</Box>

							<Box mt={2} mb={1}>
								<b>Flash Cookies.</b> Certain features of our
								Service may use local stored objects (or Flash
								Cookies) to collect and store information about
								Your preferences or Your activity on our
								Service. Flash Cookies are not managed by the
								same browser settings as those used for Browser
								Cookies. For more information on how You can
								delete Flash Cookies, please read{' '}
								{
									"'Where can I change the settings for disabling, or deleting local shared objects?'"
								}{' '}
								available at
								https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_
							</Box>

							<Box mt={2} mb={1}>
								<b>Web Beacons.</b> Certain sections of our
								Service and our emails may contain small
								electronic files known as web beacons (also
								referred to as clear gifs, pixel tags, and
								single-pixel gifs) that permit the Company, for
								example, to count users who have visited those
								pages or opened an email and for other related
								website statistics (for example, recording the
								popularity of a certain section and verifying
								system and server integrity).
							</Box>

							<Box mt={2} mb={1}>
								Cookies can be {"'Persistent'"} or {"'Session'"}
								Cookies. Persistent Cookies remain on Your
								personal computer or mobile device when You go
								offline, while Session Cookies are deleted as
								soon as You close Your web browser. You can
								learn more about cookies here: All About Cookies
								by TermsFeed.
							</Box>
						</Box>
					</Box>
					<Box sx={{ mb: 1, mt: 2 }}>
						We use both Session and Persistent Cookies for the
						purposes set out below:
						<br></br>
						<br></br>
						<b>Necessary / Essential Cookies</b>
						<br></br>
						<br></br>
						Type: Session Cookies <br></br>
						<br></br>
						Administered by: Us
						<br></br>
						<br></br>
						Purpose: These Cookies are essential to provide You with
						services available through the Website and to enable You
						to use some of its features. They help to authenticate
						users and prevent fraudulent use of user accounts.
						Without these Cookies, the services that You have asked
						for cannot be provided, and We only use these Cookies to
						provide You with those services.
						<Box mt={2} mb={2}>
							<b>Cookies Policy / Notice Acceptance Cookies</b>
						</Box>
						<Box mt={2} mb={2}>
							Type: Persistent Cookies
						</Box>
						<Box mt={2} mb={2}>
							Administered by: Us
						</Box>
						<Box mt={2} mb={2}>
							Purpose: These Cookies identify if users have
							accepted the use of cookies on the Website.
						</Box>
						<Box mt={2} mb={2}>
							<b>Functionality Cookies</b>
						</Box>
						<Box mt={2} mb={2}>
							Type: Persistent Cookies
						</Box>
						<Box mt={2} mb={2}>
							Administered by: Us
						</Box>
						<Box mt={2} mb={2}>
							Purpose: These Cookies allow us to remember choices
							You make when You use the Website, such as
							remembering your login details or language
							preference. The purpose of these Cookies is to
							provide You with a more personal experience and to
							avoid You having to re-enter your preferences every
							time You use the Website.
						</Box>
						<Box mt={2} mb={2}>
							<b>Tracking and Performance Cookies</b>
						</Box>
						<Box mt={2} mb={2}>
							Type: Persistent Cookies
						</Box>
						<Box mt={2} mb={2}>
							Administered by: Third-Parties
						</Box>
						<Box mt={2} mb={2}>
							Purpose: These Cookies are used to track information
							about traffic to the Website and how users use the
							Website. The information gathered via these Cookies
							may directly or indirectly identify you as an
							individual visitor. This is because the information
							collected is typically linked to a pseudonymous
							identifier associated with the device you use to
							access the Website. We may also use these Cookies to
							test new pages, features or new functionality of the
							Website to see how our users react to them.
						</Box>
						<Box mt={2} mb={2}>
							<b>Targeting and Advertising Cookies</b>
						</Box>
						<Box mt={2} mb={2}>
							Type: Persistent Cookies
						</Box>
						<Box mt={2} mb={2}>
							Administered by: Third-Parties
						</Box>
						<Box mt={2} mb={2}>
							Purpose: These Cookies track your browsing habits to
							enable Us to show advertising which is more likely
							to be of interest to You. These Cookies use
							information about your browsing history to group You
							with other users who have similar interests. Based
							on that information, and with Our permission, third
							party advertisers can place Cookies to enable them
							to show adverts which We think will be relevant to
							your interests while You are on third party
							websites.
						</Box>
						<Box mt={2} mb={2}>
							For more information about the cookies we use and
							your choices regarding cookies, please visit our
							Cookies Policy or the Cookies section of our Privacy
							Policy.
						</Box>
						<Box mt={2} mb={2}>
							Use of Your Personal Data <br></br>The Company may
							use Personal Data for the following purposes:
						</Box>
						<Box mt={2} mb={1}>
							<b>To provide and maintain our Service</b>,
							including to monitor the usage of our Service.
						</Box>
						<Box mt={2} mb={1}>
							<b>To manage Your Account:</b> to manage Your
							registration as a user of the Service. The Personal
							Data You provide can give You access to different
							functionalities of the Service that are available to
							You as a registered user.
						</Box>
						<Box mt={2} mb={1}>
							<b>For the performance of a contract:</b> the
							development, compliance and undertaking of the
							purchase contract for the products, items or
							services You have purchased or of any other contract
							with Us through the Service.
						</Box>
						<Box mt={2} mb={1}>
							<b>To contact You:</b> To contact You by email,
							telephone calls, SMS, or other equivalent forms of
							electronic communication, such as a mobile
							{"application's"} push notifications regarding
							updates or informative communications related to the
							functionalities, products or contracted services,
							including the security updates, when necessary or
							reasonable for their implementation.
						</Box>
						<Box mt={2} mb={1}>
							<b>To provide You</b> with news, special offers and
							general information about other goods, services and
							events which we offer that are similar to those that
							you have already purchased or enquired about unless
							You have opted not to receive such information.
						</Box>
						<Box mt={2} mb={1}>
							<b>To manage Your requests:</b> To attend and manage
							Your requests to Us.
						</Box>
						<Box mt={2} mb={1}>
							<b>To deliver targeted advertising to You:</b> We
							may use Your information to develop and display
							content and advertising (and work with third-party
							vendors who do so) tailored to Your interests and/or
							location and to measure its effectiveness.
						</Box>
						<Box mt={2} mb={1}>
							<b>For business transfers:</b> We may use Your
							information to evaluate or conduct a merger,
							divestiture, restructuring, reorganization,
							dissolution, or other sale or transfer of some or
							all of Our assets, whether as a going concern or as
							part of bankruptcy, liquidation, or similar
							proceeding, in which Personal Data held by Us about
							our Service users is among the assets transferred.
						</Box>
						<Box mt={2} mb={1}>
							<b>For other purposes:</b> We may use Your
							information for other purposes, such as data
							analysis, identifying usage trends, determining the
							effectiveness of our promotional campaigns and to
							evaluate and improve our Service, products,
							services, marketing and your experience.
						</Box>
						<Box mt={2} mb={1}>
							We may share Your personal information in the
							following situations:
						</Box>
						<Box mt={2} mb={1}>
							<b>With Service Providers:</b> We may share Your
							personal information with Service Providers to
							monitor and analyze the use of our Service, to show
							advertisements to You to help support and maintain
							Our Service, to advertise on third party websites to
							You after You visited our Service, for payment
							processing, to contact You.
						</Box>
						<Box mt={2} mb={1}>
							<b>For business transfers:</b> We may share or
							transfer Your personal information in connection
							with, or during negotiations of, any merger, sale of
							Company assets, financing, or acquisition of all or
							a portion of Our business to another company.
						</Box>
						<Box mt={2} mb={1}>
							<b>With Affiliates:</b> We may share Your
							information with Our affiliates, in which case we
							will require those affiliates to honor this Privacy
							Policy. Affiliates include Our parent company and
							any other subsidiaries, joint venture partners or
							other companies that We control or that are under
							common control with Us.
						</Box>
						<Box mt={2} mb={1}>
							<b>With business partners:</b> We may share Your
							information with Our business partners to offer You
							certain products, services or promotions.
						</Box>
						<Box mt={2} mb={1}>
							<b>With other users:</b> When You share personal
							information or otherwise interact in the public
							areas with other users, such information may be
							viewed by all users and may be publicly distributed
							outside. If You interact with other users or
							register through a Third-Party Social Media Service,
							Your contacts on the Third-Party Social Media
							Service may see Your name, profile, pictures and
							description of Your activity. Similarly, other users
							will be able to view descriptions of Your activity,
							communicate with You and view Your profile.
						</Box>
						<Box mt={2} mb={1}>
							<b>With Your consent:</b> We may disclose Your
							personal information for any other purpose with Your
							consent.
						</Box>
					</Box>
					<Box sx={{ mb: 1, mt: 2 }}>
						Retention of Your Personal Data
						<br></br>
						The Company will retain Your Personal Data only for as
						long as is necessary for the purposes set out in this
						Privacy Policy. We will retain and use Your Personal
						Data to the extent necessary to comply with our legal
						obligations (for example, if we are required to retain
						your data to comply with applicable laws), resolve
						disputes, and enforce our legal agreements and policies.
						<Box mt={2} mb={2}>
							The Company will also retain Usage Data for internal
							analysis purposes. Usage Data is generally retained
							for a shorter period of time, except when this data
							is used to strengthen the security or to improve the
							functionality of Our Service, or We are legally
							obligated to retain this data for longer time
							periods.
						</Box>
					</Box>
					<Box sx={{ mb: 1, mt: 2 }}>
						Transfer of Your Personal Data
						<br></br>
						Your information, including Personal Data, is processed
						at the {"Company's"} operating offices and in any other
						places where the parties involved in the processing are
						located. It means that this information may be
						transferred to — and maintained on — computers located
						outside of Your state, province, country or other
						governmental jurisdiction where the data protection laws
						may differ than those from Your jurisdiction.
					</Box>
					<Box sx={{ mb: 1, mt: 2 }}>
						Your consent to this Privacy Policy followed by Your
						submission of such information represents Your agreement
						to that transfer.
					</Box>
					<Box sx={{ mb: 1, mt: 2 }}>
						The Company will take all steps reasonably necessary to
						ensure that Your data is treated securely and in
						accordance with this Privacy Policy and no transfer of
						Your Personal Data will take place to an organization or
						a country unless there are adequate controls in place
						including the security of Your data and other personal
						information.
					</Box>
					<Box sx={{ mb: 1, mt: 2 }}>
						Disclosure of Your Personal Data
					</Box>
					<h2>Business Transactions</h2>
					<Box mt={2} mb={2}>
						If the Company is involved in a merger, acquisition or
						asset sale, Your Personal Data may be transferred. We
						will provide notice before Your Personal Data is
						transferred and becomes subject to a different Privacy
						Policy.
					</Box>
					<h2>Law enforcement</h2>
					<Box mt={2} mb={2}>
						Under certain circumstances, the Company may be required
						to disclose Your Personal Data if required to do so by
						law or in response to valid requests by public
						authorities (e.g. a court or a government agency).
					</Box>
					<h2>Other legal requirements</h2>
					<Box mt={2} mb={2}>
						The Company may disclose Your Personal Data in the good
						faith belief that such action is necessary to:
					</Box>
					<Box mt={2} mb={2}>
						Comply with a legal obligation
						<br></br>
						Protect and defend the rights or property of the Company
						<br></br>
						Prevent or investigate possible wrongdoing in connection
						with the Service
						<br></br>
						Protect the personal safety of Users of the Service or
						the public
						<br></br>
						Protect against legal liability
						<br></br>
						Security of Your Personal Data
						<br></br>
						The security of Your Personal Data is important to Us,
						but remember that no method of transmission over the
						Internet, or method of electronic storage is 100%
						secure. While We strive to use commercially acceptable
						means to protect Your Personal Data, We cannot guarantee
						its absolute security.
					</Box>
					<Box mt={4} mb={5}>
						Detailed Information on the Processing of Your Personal
						Data
						<br></br>
						The Service Providers We use may have access to Your
						Personal Data. These third-party vendors collect, store,
						use, process and transfer information about Your
						activity on Our Service in accordance with their Privacy
						Policies.
					</Box>
					<Box sx={{ mb: 1, mt: 2 }}>
						Analytics
						<br></br>We may use third-party Service providers to
						monitor and analyze the use of our Service.
						<br></br>
						<br></br>
						<b>Google Analytics</b>
						<br></br>
						<br></br>Google Analytics is a web analytics service
						offered by Google that tracks and reports website
						traffic. Google uses the data collected to track and
						monitor the use of our Service. This data is shared with
						other Google services. Google may use the collected data
						to contextualize and personalize the ads of its own
						advertising network.
						<br></br>
						<br></br>
						You can opt-out of having made your activity on the
						Service available to Google Analytics by installing the
						Google Analytics opt-out browser add-on. The add-on
						prevents the Google Analytics JavaScript (ga.js,
						analytics.js and dc.js) from sharing information with
						Google Analytics about visits activity.
						<br></br>
						You may opt-out of certain Google Analytics features
						through your mobile device settings, such as your device
						advertising settings or by following the instructions
						provided by Google in their Privacy Policy:
						https://policies.google.com/privacy
						<br></br>
						<br></br>
						For more information on the privacy practices of Google,
						please visit the Google Privacy & Terms web page:
						https://policies.google.com/privacy
						<br></br>
						<br></br>
						<b>Firebase</b>
						<br></br>
						<br></br>Firebase is an analytics service provided by
						Google Inc.
						<br></br>
						<br></br>
						You may opt-out of certain Google Analytics features
						through your mobile device settings, such as your device
						advertising settings or by following the instructions
						provided by Google in their Privacy Policy:
						https://policies.google.com/privacy
						<br></br>
						<br></br>
						We also encourage you to review the {"Google's"} policy
						for safeguarding your data:
						https://support.google.com/analytics/answer/6004245
						<br></br>
						<br></br>
						For more information on what type of information
						Firebase collects, please visit the How Google uses data
						when you use our {"partners'"} sites or apps webpage:
						https://policies.google.com/technologies/partner-sites
						<br></br>
						<br></br>
						Advertising
						<br></br>
						We may use Service Providers to show advertisements to
						You to help support and maintain Our Service.
						<br></br>
						<br></br>
						<b>Google AdSense & DoubleClick Cookie</b>
						<br></br>
						<br></br>
						Google, as a third party vendor, uses cookies to serve
						ads on our Service. {"Google's"} use of the DoubleClick
						cookie enables it and its partners to serve ads to our
						users based on their visit to our Service or other
						websites on the Internet.
						<br></br>
						<br></br>
						You may opt out of the use of the DoubleClick Cookie for
						interest-based advertising by visiting the Google Ads
						Settings web page:
						http://www.google.com/ads/preferences/
						<br></br>
						<br></br>
						Email Marketing
						<br></br>
						We may use Your Personal Data to contact You with
						newsletters, marketing or promotional materials and
						other information that may be of interest to You. You
						may opt-out of receiving any, or all, of these
						communications from Us by following the unsubscribe link
						or instructions provided in any email We send or by
						contacting Us.
						<br></br>
						<br></br>
						We may use Email Marketing Service Providers to manage
						and send emails to You.
						<br></br>
						<br></br>
						<b>Mailchimp</b>
						<br></br>
						<br></br>
						Mailchimp is an email marketing sending service provided
						by The Rocket Science Group LLC.
						<br></br>
						<br></br>
						For more information on the privacy practices of
						Mailchimp, please visit their Privacy policy:
						https://mailchimp.com/legal/privacy/
						<br></br>
						<br></br>
						Payments
						<br></br>
						We may provide paid products and/or services within the
						Service. In that case, we may use third-party services
						for payment processing (e.g. payment processors).
						<br></br>
						<br></br>
						We will not store or collect Your payment card details.
						That information is provided directly to Our third-party
						payment processors whose use of Your personal
						information is governed by their Privacy Policy. These
						payment processors adhere to the standards set by
						PCI-DSS as managed by the PCI Security Standards
						Council, which is a joint effort of brands like Visa,
						Mastercard, American Express and Discover. PCI-DSS
						requirements help ensure the secure handling of payment
						information. We will not store or collect Your payment
						card details. That information is provided directly to
						Our third-party payment processors whose use of Your
						personal information is governed by their Privacy
						Policy. These payment processors adhere to the standards
						set by PCI-DSS as managed by the PCI Security Standards
						Council, which is a joint effort of brands like Visa,
						Mastercard, American Express and Discover. PCI-DSS
						requirements help ensure the secure handling of payment
						information.
						<br></br>
						<br></br>
						<b>Apple Store In-App Payments</b>
						<br></br>
						<br></br>
						Their Privacy Policy can be viewed at
						https://www.apple.com/legal/privacy/en-ww/
						<br></br>
						<br></br>
						<b>Google Play In-App Payments</b>
						<br></br>
						<br></br>
						Their Privacy Policy can be viewed at
						https://www.google.com/policies/privacy/
						<br></br>
						<br></br>
						<b>Stripe</b>
						<br></br>
						<br></br>
						Their Privacy Policy can be viewed at
						https://stripe.com/us/privacy
						<br></br>
						<br></br>
						<b>WePay</b>
						<br></br>
						<br></br>
						Their Privacy Policy can be viewed at
						https://go.wepay.com/privacy-policy
						<br></br>
						<br></br>
						<b>WeChat</b>
						<br></br>
						<br></br>
						Their Privacy Policy can be viewed at
						https://www.wechat.com/en/privacy_policy.html
						<br></br>
						<br></br>
						<b>Alipay</b>
						<br></br>
						<br></br>
						Their Privacy Policy can be viewed at
						https://render.alipay.com/p/f/agreementpages/alipayglobalprivacypolicy.html
						<br></br>
						<br></br>
						Behavioral Remarketing
						<br></br>
						The Company uses remarketing services to advertise to
						You after You accessed or visited our Service. We and
						Our third-party vendors use cookies and non-cookie
						technologies to help Us recognize Your Device and
						understand how You use our Service so that We can
						improve our Service to reflect Your interests and serve
						You advertisements that are likely to be of more
						interest to You.
						<br></br>
						<br></br>
						These third-party vendors collect, store, use, process
						and transfer information about Your activity on Our
						Service in accordance with their Privacy Policies and to
						enable Us to:
						<br></br>
						<br></br>
						Measure and analyze traffic and browsing activity on Our
						Service
						<br></br>
						Show advertisements for our products and/or services to
						You on third-party websites or apps
						<br></br>
						Measure and analyze the performance of Our advertising
						campaigns
						<br></br>
						Some of these third-party vendors may use non-cookie
						technologies that may not be impacted by browser
						settings that block cookies. Your browser may not permit
						You to block such technologies. You can use the
						following third-party tools to decline the collection
						and use of information for the purpose of serving You
						interest-based advertising:
						<br></br>
						<br></br>
						The {"NAI's"} opt-out platform:
						http://www.networkadvertising.org/choices/
						<br></br>
						The {"EDAA's"} opt-out platform:
						http://www.youronlinechoices.com/
						<br></br>
						The {"DAA's"} opt-out platform:
						http://optout.aboutads.info/?c=2&lang=EN
						<br></br>
						You may opt-out of all personalized advertising by
						enabling privacy features on Your mobile device such as
						Limit Ad Tracking (iOS) and Opt Out of Ads
						Personalization (Android). See Your mobile device Help
						system for more information.
						<br></br>
						<br></br>
						We may share information, such as hashed email addresses
						(if available) or other online identifiers collected on
						Our Service with these third-party vendors. This allows
						Our third-party vendors to recognize and deliver You ads
						across devices and browsers. To read more about the
						technologies used by these third-party vendors and their
						cross-device capabilities please refer to the Privacy
						Policy of each vendor listed below.
						<br></br>
						<br></br>
						The third-party vendors We use are:
						<br></br>
						<br></br>
						<b>Google Ads (AdWords)</b>
						<br></br>
						<br></br>
						You can opt-out of Google Analytics for Display
						Advertising and customise the Google Display Network ads
						by visiting the Google Ads Settings page:
						http://www.google.com/settings/ads
						<br></br>
						<br></br>
						Google also recommends installing the Google Analytics
						Opt-out Browser Add-on -
						https://tools.google.com/dlpage/gaoptout for your web
						browser. Google Analytics Opt-out Browser Add-on
						provides visitors with the ability to prevent their data
						from being collected and used by Google Analytics.
						<br></br>
						<br></br>
						For more information on the privacy practices of Google,
						please visit the Google Privacy & Terms web page:
						https://policies.google.com/privacy
						<br></br>
						<br></br>
						<b>Bing Ads Remarketing</b>
						<br></br>
						<br></br>
						Bing Ads remarketing service is provided by Microsoft
						Inc.
						<br></br>
						<br></br>
						You can opt-out of Bing Ads interest-based ads by
						following their instructions:
						https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads
						<br></br>
						<br></br>
						You can learn more about the privacy practices and
						policies of Microsoft by visiting their Privacy Policy
						page:
						https://privacy.microsoft.com/en-us/PrivacyStatement
						<br></br>
						<br></br>
						<b>Facebook</b>
						<br></br>
						<br></br>
						Facebook remarketing service is provided by Facebook
						Inc.
						<br></br>
						<br></br>
						You can learn more about interest-based advertising from
						Facebook by visiting this page:
						https://www.facebook.com/help/516147308587266
						<br></br>
						<br></br>
						To opt-out from {"Facebook's"} interest-based ads,
						follow these instructions from Facebook:
						https://www.facebook.com/help/568137493302217
						<br></br>
						<br></br>
						Facebook adheres to the Self-Regulatory Principles for
						Online Behavioural Advertising established by the
						Digital Advertising Alliance. You can also opt-out from
						Facebook and other participating companies through the
						Digital Advertising Alliance in the USA
						http://www.aboutads.info/choices/, the Digital
						Advertising Alliance of Canada in Canada
						http://youradchoices.ca/ or the European Interactive
						Digital Advertising Alliance in Europe
						http://www.youronlinechoices.eu/, or opt-out using your
						mobile device settings.
						<br></br>
						<br></br>
						For more information on the privacy practices of
						Facebook, please visit {"Facebook's"} Data Policy:
						https://www.facebook.com/privacy/explanation
						<br></br>
						<br></br>
						<b>Pinterest</b>
						<br></br>
						<br></br>
						Pinterest remarketing service is provided by Pinterest
						Inc.
						<br></br>
						<br></br>
						You can opt-out from {"Pinterest's"} interest-based ads
						by enabling the {"'Do Not Track'"} functionality of your
						web browser or by following Pinterest instructions:
						http://help.pinterest.com/en/articles/personalization-and-data
						<br></br>
						<br></br>
						You can learn more about the privacy practices and
						policies of Pinterest by visiting their Privacy Policy
						page: https://about.pinterest.com/en/privacy-policy
						<br></br>
						<br></br>
						<b>AdRoll</b>
						<br></br>
						<br></br>
						AdRoll remarketing service is provided by NextRoll, Inc.
						<br></br>
						<br></br>
						You can opt-out of AdRoll remarketing by visiting this
						AdRoll Advertising Preferences web page:
						http://info.evidon.com/pub_info/573?v=1&nt=1&nw=false or
						the Opt Out of Personalized Advertising web page:
						https://help.adroll.com/hc/en-us/articles/216599538-Opting-Out-of-Personalized-Advertising
						<br></br>
						<br></br>
						If You are a California resident, please read the
						{"'Information For California Residents Only'"} section
						in the Privacy Policy of NextRoll, Inc.:
						https://www.nextroll.com/privacy#service-13
						<br></br>
						<br></br>
						For more information on the privacy practices of AdRoll,
						please visit the NextRoll, Inc. Privacy Policy web page:
						https://www.nextroll.com/privacy
					</Box>
					<Box sx={{ mb: 1, mt: 3 }}>
						{"Children's"} Privacy
						<br></br>
						Our Service does not address anyone under the age of 13.
						We do not knowingly collect personally identifiable
						information from anyone under the age of 13. If You are
						a parent or guardian and You are aware that Your child
						has provided Us with Personal Data, please contact Us.
						If We become aware that We have collected Personal Data
						from anyone under the age of 13 without verification of
						parental consent, We take steps to remove that
						information from Our servers.
						<br></br>
						<br></br>
						If We need to rely on consent as a legal basis for
						processing Your information and Your country requires
						consent from a parent, We may require Your {"parent's"}
						consent before We collect and use that information.
					</Box>
					<Box sx={{ mb: 1, mt: 3 }}>
						Links to Other Websites
						<br></br>
						Our Service may contain links to other websites that are
						not operated by Us. If You click on a third party link,
						You will be directed to that third {"party's"} site. We
						strongly advise You to review the Privacy Policy of
						every site You visit.
						<br></br>
						<br></br>
						We have no control over and assume no responsibility for
						the content, privacy policies or practices of any third
						party sites or services.
					</Box>
					<Box sx={{ mb: 1, mt: 3 }}>
						Changes to this Privacy Policy
						<br></br>
						We may update Our Privacy Policy from time to time. We
						will notify You of any changes by posting the new
						Privacy Policy on this page.
						<br></br>
						<br></br>
						We will let You know via email and/or a prominent notice
						on Our Service, prior to the change becoming effective
						and update the {"'Last updated'"} date at the top of
						this Privacy Policy.
						<br></br>
						<br></br>
						You are advised to review this Privacy Policy
						periodically for any changes. Changes to this Privacy
						Policy are effective when they are posted on this page.
					</Box>
					<Box sx={{ mb: 1, mt: 3 }}>
						Contact Us <br></br>If you have any questions about
						these Terms and Conditions, You can contact us:
						<br></br>
						<br></br>
						By visiting this page on our website: www.umego.io
						<br></br>
						By email: hello@umego.io
					</Box>
				</Box>
			</Container>
		</>
	);
};

export default PrivacyPolicy;
